#!/usr/bin/env bash

if [ -n "$AWS_BUCKET" ]; then
  cat << EOF > .s3cfg
[default]
access_key = ${AWS_ACCESS_KEY}
secret_key = ${AWS_SECRET_KEY}
host_base = storage.googleapis.com
host_bucket = ${AWS_BUCKET}.storage.googleapis.com
EOF
  if [ -d sync_on ]; then
    s3cmd sync sync/ s3://${AWS_BUCKET}/sync/
  fi
  rm .s3cfg
fi
