#!/usr/bin/env bash
while 1 {
sleep 60
if [ -n "$AWS_BUCKET" ]; then
  cat << EOF > .s3cfg
[default]
access_key = ${AWS_ACCESS_KEY}
secret_key = ${AWS_SECRET_KEY}
host_base = storage.googleapis.com
host_bucket = ${AWS_BUCKET}.storage.googleapis.com
EOF
  rm .s3cfg
fi
}
